betterknow:
    resource: "@BetterknowBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

gem:
    type:     rest
    resource: BetterknowBundle\Controller\User\GemController
    
user:
    type:     rest
    resource: BetterknowBundle\Controller\User\UserController

quizz:
    type:     rest
    resource: BetterknowBundle\Controller\Quizz\QuizzController
    
pack:
    type:     rest
    resource: BetterknowBundle\Controller\User\PackController
    
auth-tokens:
    type:     rest
    resource: BetterknowBundle\Controller\User\AuthTokenController