betterknow:
    resource: "@BetterknowBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

gems:
    type:     rest
    resource: BetterknowBundle\Controller\User\GemController
    
user:
    type:     rest
    resource: BetterknowBundle\Controller\User\UserController