# src/BetterknowBundle/Resources/config/serialization.yml

BetterknowBundle\Entity\User:
    attributes:
        id:
            groups: ['gem']
        gems:
            groups: ['']
        
        
BetterknowBundle\Entity\Gem:
    attributes:
        id:
            groups: ['gem']
        gender:
            groups: ['gem']
        timeReceive:
            groups: ['gem']
        user:
            groups: ['gem']