# src/BetterknowBundle/Resources/config/serialization.yml

BetterknowBundle\Entity\User:
    attributes:
        id:
            groups: ['gem', 'user', 'friend', 'quizz', 'response']
        username:
            groups: ['user', 'auth-token', 'friend', 'response']
        firstName:
            groups: ['user', 'auth-token', 'friend', 'response']
        lastName:
            groups: ['user', 'auth-token', 'friend', 'response']
        age:
            groups: ['user', 'auth-token', 'friend']
        email:
            groups: ['user', 'auth-token']
        gender:
            groups: ['user', 'auth-token', 'friend']

BetterknowBundle\Entity\Friend:
    attributes:
        id:
            groups: ['friend']
        state:
            groups: ['friend', 'quizz', 'response']
        friend:
            groups: ['friend', 'quizz', 'response']
        user:
            groups: ['confirmShip']

BetterknowBundle\Entity\Pack:
    attributes:
        id:
            groups: ['pack']
        theme:
            groups: ['pack']
        quizz:
            groups: ['pack']
            
BetterknowBundle\Entity\Quizz:
    attributes:
        id:
            groups: ['quizz', 'pack']
        question:
            groups: ['quizz', 'pack']
        responses:
            groups: ['quizz']
            

BetterknowBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']
        
BetterknowBundle\Entity\Gem:
    attributes:
        id:
            groups: ['gem']
        gender:
            groups: ['gem']
        timeReceive:
            groups: ['gem']
        user:
            groups: ['gem']