# src/BetterknowBundle/Resources/config/serialization.yml

BetterknowBundle\Entity\User:
    attributes:
        id:
            groups: ['gem', 'user']
        username:
            groups: ['user']
        firstName:
            groups: ['user']
        lastName:
            groups: ['user']
        age:
            groups: ['user']
        email:
            groups: ['user']
        gender:
            groups: ['user']
        gems:
            groups: ['']
        
        
BetterknowBundle\Entity\Gem:
    attributes:
        id:
            groups: ['gem']
        gender:
            groups: ['gem']
        timeReceive:
            groups: ['gem']
        user:
            groups: ['gem']