services:
#    betterknow.example:
#        class: BetterknowBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    bk.form.registration:
        class: BetterknowBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: bk_user_registration }
