<?php

namespace BetterknowBundle\Repository;

/**
 * GemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GemRepository extends \Doctrine\ORM\EntityRepository
{
}
